security:
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        api_token_user_provider:
            memory:
                users:
                    api-client:
                        password: '$2y$13$dummyNotUsed'
                        roles: [ 'ROLE_API' ]

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
            # API firewall: Bearer token required (stateless)

        # https://symfony.com/doc/current/security/access_token.html
        api:
            pattern: ^/api
            stateless: true
            provider: api_token_user_provider
            access_token:
                token_handler: App\Security\ApiAccessTokenHandler

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # only public endpoint
        - { path: ^/api/channels$, roles: PUBLIC_ACCESS }

        # everything else passes through ApiAccessTokenHandler
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
